server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  application:
    name: sc-demo
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sc-demo
    username: root
    password: yun1206
    hikari:
      connection-test-query: "select 1"
      validation-timeout: 30000
      auto-commit: false
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 60000
#  r2dbc:
#    url: r2dbc:mariadb://localhost:3306/sc-demo
#    username: root
#    password: yun1206
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
        default_batch_fetch_size: 500
        format_sql: true
#        bytecode:
#          use_reflection_optimizer: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: sc-demo


springdoc:
  packages-to-scan: com.example.javaboilerplate
  swagger-ui:
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

webclient:
  local:
    base-url: http://localhost:8080
---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stage

---
spring:
  config:
    activate:
      on-profile: prod