server:
  port: 8080

spring:
  application:
    name: sc-demo
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sc-demo
    username: root
    password: yun1206
    hikari:
      connection-test-query: "select 1"
      validation-timeout: 2000
      auto-commit: false
      maximum-pool-size: 10
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 500
springdoc:
  packages-to-scan: com.example.javaboilerplate
  swagger-ui:
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stage

---
spring:
  config:
    activate:
      on-profile: prod