version: '3.8'

services:
  # k6 성능 테스트 서비스
  k6:
    image: grafana/k6:latest
    container_name: k6-cache-tester
    networks:
      - k6-network
    volumes:
      - ./k6:/scripts
      - ./results:/results
    environment:
      - BASE_URL=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      run --out json=/results/cache-performance-results.json
      --summary-export=/results/summary.json
      /scripts/cache-performance-test.js
    depends_on:
      - grafana
      - influxdb
    profiles:
      - performance

  # k6 스트레스 테스트
  k6-stress:
    image: grafana/k6:latest
    container_name: k6-stress-tester
    networks:
      - k6-network
    volumes:
      - ./k6:/scripts
      - ./results:/results
    environment:
      - BASE_URL=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      run --out json=/results/cache-stress-results.json
      --summary-export=/results/stress-summary.json
      /scripts/cache-stress-test.js
    depends_on:
      - grafana
      - influxdb
    profiles:
      - stress

  # k6 스파이크 테스트
  k6-spike:
    image: grafana/k6:latest
    container_name: k6-spike-tester
    networks:
      - k6-network
    volumes:
      - ./k6:/scripts
      - ./results:/results
    environment:
      - BASE_URL=http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      run --out json=/results/cache-spike-results.json
      --summary-export=/results/spike-summary.json
      /scripts/cache-spike-test.js
    depends_on:
      - grafana
      - influxdb
    profiles:
      - spike

  # InfluxDB - 메트릭 저장소
  influxdb:
    image: influxdb:1.8
    container_name: k6-influxdb
    networks:
      - k6-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6password
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb_data:/var/lib/influxdb
    profiles:
      - monitoring

  # Grafana - 메트릭 시각화
  grafana:
    image: grafana/grafana:latest
    container_name: k6-grafana
    networks:
      - k6-network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb
    profiles:
      - monitoring

  # k6 with InfluxDB output (실시간 모니터링)
  k6-live:
    image: grafana/k6:latest
    container_name: k6-live-tester
    networks:
      - k6-network
    volumes:
      - ./k6:/scripts
      - ./results:/results
    environment:
      - BASE_URL=http://host.docker.internal:8080
      - K6_OUT=influxdb=http://influxdb:8086/k6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      run --out influxdb=http://influxdb:8086/k6
      --tag testid=cache-performance-live
      /scripts/cache-performance-test.js
    depends_on:
      - influxdb
    profiles:
      - live

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  k6-network:
    driver: bridge